#################################
###        NOT FINISHED       ###
#################################


FROM consol/ubuntu-xfce-vnc
#https://hub.docker.com/r/consol/ubuntu-xfce-vnc/


MAINTAINER lennart.heim@rwth-aachen.de


#apt-get install software properties-common
#add-apt-repository ppa:regar42/openbts
#apt-get update

#pw: vncpassword


ENV USRP_IP=10.0.0.11


#vnc port
EXPOSE 5901

#vnc-web port
EXPOSE 6901
